name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: koledin0ci # optional
        # Password or personal access token used to log against the Docker registry
        password: "dckr_pat_ulo0Ws-wNVtwHCOseLOmZ1gn3Es" # optional
    - name: Build the Docker image
      run: cd backend; docker build . --file Dockerfile --tag docker.io/koledin0ci/strapi:latest && docker push docker.io/koledin0ci/strapi:latest
    - name: Build the Docker image
      run: cd frontend; docker build . --file Dockerfile --tag docker.io/koledin0ci/nextjs:latest && docker push docker.io/koledin0ci/nextjs:latest
    - name: Trigger remote
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: koledin.com
        username: root
        password: nauka2021
        port: 22
        script: cd /root/koledin-design/backend; docker-compose down && docker-compose pull -q && docker-compose up -d && docker rmi `docker images -q` || true
